Repository zippick/zippick-frontend, pull requests merged in 2025-07, with the labels that each got.

#12 [FEAT] Ai 가구 배치 페이지 구현
  Zippick/.idea/AndroidProjectSystem.xml
  Zippick/.idea/compiler.xml
  Zippick/.idea/deploymentTargetSelector.xml
  Zippick/.idea/gradle.xml
  Zippick/.idea/migrations.xml
  Zippick/.idea/misc.xml
  Zippick/.idea/runConfigurations.xml
  Zippick/.idea/vcs.xml
  Zippick/app/build.gradle.kts
  Zippick/app/src/main/java/com/example/zippick/network/FakeAiCombineApi.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/MainScreenWithBottomNav.kt
  Zippick/app/src/main/java/com/example/zippick/ui/model/dummy/AiCombineRequest.kt
  Zippick/app/src/main/java/com/example/zippick/ui/screen/AiCombinedScreen.kt
  Zippick/app/src/main/res/drawable/ai_combine.png
Labels: feat

#13 [FEAT] 상품 상세페이지 구현
  Zippick/app/src/main/java/com/example/zippick/ui/composable/BottomBar.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/MainScreenWithBottomNav.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/TopBar.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/category/FilterChip.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/category/ProductGrid.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/category/ProductItem.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/detail/AIVirtualPlacementButton.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/detail/DetailRow.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/detail/ProductDetailContent.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/home/CategoryCard.kt
  Zippick/app/src/main/java/com/example/zippick/ui/model/Product.kt
  Zippick/app/src/main/java/com/example/zippick/ui/model/ProductDetail.kt
  Zippick/app/src/main/java/com/example/zippick/ui/model/dummy/sampleProductDetail.kt
  Zippick/app/src/main/java/com/example/zippick/ui/model/dummy/sampleProducts.kt
  Zippick/app/src/main/java/com/example/zippick/ui/screen/CategoryScreen.kt
  Zippick/app/src/main/java/com/example/zippick/ui/screen/DetailScreen.kt
  Zippick/app/src/main/java/com/example/zippick/ui/screen/HomeScreen.kt
  Zippick/app/src/main/java/com/example/zippick/ui/theme/Color.kt
  Zippick/app/src/main/java/com/example/zippick/ui/theme/Type.kt
  Zippick/app/src/main/res/drawable/ai_icon.png
  Zippick/app/src/main/res/drawable/product_detail.webp
  Zippick/app/src/main/res/drawable/thumnail.webp
  Zippick/app/src/main/res/font/pretendard_bold.ttf
  Zippick/app/src/main/res/font/pretendard_extrabold.ttf
  Zippick/app/src/main/res/font/pretendard_medium.ttf
  Zippick/app/src/main/res/font/pretendard_regular.ttf
Labels: feat

#17 [FEAT] 공간 이미지 기반 추천 사용자 입력 페이지 구현
  Zippick/app/src/main/java/com/example/zippick/ui/composable/photo/AnalyzeButton.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/photo/CategorySelector.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/photo/PhotoUploadSection.kt
  Zippick/app/src/main/java/com/example/zippick/ui/screen/PhotoScreen.kt
  Zippick/app/src/main/res/drawable/ai_recommand.png
Labels: feat

#22 [FEAT] 가구 검색 페이지 추가
  Zippick/app/src/main/java/com/example/zippick/ui/composable/sizeSearch/ProductSorterForSize.kt
  Zippick/app/src/main/java/com/example/zippick/ui/screen/SearchScreen.kt
  Zippick/app/src/main/java/com/example/zippick/ui/screen/SizeSearchResultScreen.kt
Labels: feat

#25 [FEAT] 공간 이미지 분석 결과 구현
  Zippick/app/src/main/java/com/example/zippick/ui/composable/BottomBar.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/MainScreenWithBottomNav.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/TopBar.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/photo/AnalyzeButton.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/photo/result/ColorPaletteSection.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/photo/result/ImageHeader.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/photo/result/RecommendButtons.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/photo/result/StyleTagSection.kt
  Zippick/app/src/main/java/com/example/zippick/ui/screen/PhotoAnalysisResultScreen.kt
  Zippick/app/src/main/java/com/example/zippick/ui/screen/PhotoScreen.kt
Labels: feat

#26 [FEAT] Retrofit 연결 및 설정
  Zippick/app/build.gradle.kts
  Zippick/app/src/main/AndroidManifest.xml
  Zippick/app/src/main/java/com/example/zippick/network/FakeAiLayoutApi.kt
  Zippick/app/src/main/java/com/example/zippick/network/FakeProductsBySizeApi.kt
  Zippick/app/src/main/java/com/example/zippick/network/RetrofitInstance.kt
  Zippick/app/src/main/java/com/example/zippick/network/product/ProductApi.kt
  Zippick/app/src/main/java/com/example/zippick/network/product/ProductRepository.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/MainScreenWithBottomNav.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/TopBar.kt
  Zippick/app/src/main/java/com/example/zippick/ui/model/AiLayout.kt
  Zippick/app/src/main/java/com/example/zippick/ui/model/ProductResponse.kt
  Zippick/app/src/main/java/com/example/zippick/ui/model/dummy/AiLayoutRequest.kt
  Zippick/app/src/main/java/com/example/zippick/ui/screen/AiLayoutScreen.kt
  Zippick/app/src/main/java/com/example/zippick/ui/screen/SizeInputScreen.kt
  Zippick/app/src/main/java/com/example/zippick/ui/screen/SizeSearchResultScreen.kt
  Zippick/app/src/main/java/com/example/zippick/ui/viewmodel/ProductViewModel.kt
  Zippick/app/src/main/res/xml/network_security_config.xml
Labels: feat

#31 feat: 마이페이지 UI
  Zippick/app/src/main/java/com/example/zippick/ui/screen/MyScreen.kt
Labels: feat

#34 [FEAT] API 연결 및 상품 목록 수정
  Zippick/app/build.gradle.kts
  Zippick/app/src/main/java/com/example/zippick/network/RetrofitInstance.kt
  Zippick/app/src/main/java/com/example/zippick/network/product/ProductApi.kt
  Zippick/app/src/main/java/com/example/zippick/network/product/ProductRepository.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/BottomBar.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/MainScreenWithBottomNav.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/category/ProductGrid.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/category/SortFilterWithBottomSheet.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/detail/ProductDetailContent.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/sizeSearch/ProductSorterForSize.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/sizeSearch/SortFilterForSizeBottomSheet.kt
  Zippick/app/src/main/java/com/example/zippick/ui/model/SizeSortOption.kt
  Zippick/app/src/main/java/com/example/zippick/ui/model/SortOption.kt
  Zippick/app/src/main/java/com/example/zippick/ui/model/dummy/sampleProductDetail.kt
  Zippick/app/src/main/java/com/example/zippick/ui/screen/AiLayoutScreen.kt
  Zippick/app/src/main/java/com/example/zippick/ui/screen/CategoryScreen.kt
  Zippick/app/src/main/java/com/example/zippick/ui/screen/SearchScreen.kt
  Zippick/app/src/main/java/com/example/zippick/ui/screen/SizeSearchResultScreen.kt
  Zippick/app/src/main/java/com/example/zippick/ui/viewmodel/ProductViewModel.kt
  Zippick/app/src/main/res/drawable/ai_result_character.png
Labels: feat

#37 [FEAT] 일반 검색 / 사이즈 검색 / AI 가구배치 API 연결
  Zippick/app/src/main/java/com/example/zippick/network/RetrofitInstance.kt
  Zippick/app/src/main/java/com/example/zippick/network/product/ProductApi.kt
  Zippick/app/src/main/java/com/example/zippick/network/product/ProductRepository.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/MainScreenWithBottomNav.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/TopBar.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/category/ProductFilterHeader.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/detail/ProductDetailContent.kt
  Zippick/app/src/main/java/com/example/zippick/ui/screen/AiLayoutScreen.kt
  Zippick/app/src/main/java/com/example/zippick/ui/screen/CategoryScreen.kt
  Zippick/app/src/main/java/com/example/zippick/ui/screen/SearchScreen.kt
  Zippick/app/src/main/java/com/example/zippick/ui/screen/SizeInputScreen.kt
  Zippick/app/src/main/java/com/example/zippick/ui/viewmodel/ProductViewModel.kt
  Zippick/app/src/main/java/com/example/zippick/util/CategoryMapper.kt
Labels: feat

#48 feat: 로그인 API 연동
  Zippick/app/src/main/java/com/example/zippick/MainActivity.kt
  Zippick/app/src/main/java/com/example/zippick/network/AuthService.kt
  Zippick/app/src/main/java/com/example/zippick/network/RetrofitInstance.kt
  Zippick/app/src/main/java/com/example/zippick/ui/model/LoginRequest.kt
  Zippick/app/src/main/java/com/example/zippick/ui/model/LoginResponse.kt
  Zippick/app/src/main/java/com/example/zippick/ui/screen/LoginScreen.kt
Labels: feat

#53 Feat/sign up api
  Zippick/app/src/main/AndroidManifest.xml
  Zippick/app/src/main/assets/postcode.html
  Zippick/app/src/main/java/com/example/zippick/WebViewActivity.kt
  Zippick/app/src/main/java/com/example/zippick/network/AuthService.kt
  Zippick/app/src/main/java/com/example/zippick/network/auth/AuthService.kt
  Zippick/app/src/main/java/com/example/zippick/network/member/MemberService.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/MainScreenWithBottomNav.kt
  Zippick/app/src/main/java/com/example/zippick/ui/model/LoginResponse.kt
  Zippick/app/src/main/java/com/example/zippick/ui/model/SignUpRequest.kt
  Zippick/app/src/main/java/com/example/zippick/ui/screen/LoginScreen.kt
  Zippick/app/src/main/java/com/example/zippick/ui/screen/SignUpScreen.kt
Labels: feat

#59 [REFACTOR] 리팩토링 및 일부 버그 수정
  Zippick/app/src/main/java/com/example/zippick/ui/composable/BottomBar.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/MainScreenWithBottomNav.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/TopBar.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/category/PriceFilterWithBottomSheet.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/category/ProductFilterHeader.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/category/ProductGrid.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/home/CategoryGrid.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/sizeSearch/InfiniteProductGrid.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/sizeSearch/ProductSorterForSize.kt
  Zippick/app/src/main/java/com/example/zippick/ui/model/SortOption.kt
  Zippick/app/src/main/java/com/example/zippick/ui/screen/AiLayoutScreen.kt
  Zippick/app/src/main/java/com/example/zippick/ui/screen/CategoryScreen.kt
  Zippick/app/src/main/java/com/example/zippick/ui/screen/HomeScreen.kt
  Zippick/app/src/main/java/com/example/zippick/ui/screen/PhotoRecommandListScreen.kt
  Zippick/app/src/main/java/com/example/zippick/ui/screen/PhotoScreen.kt
  Zippick/app/src/main/java/com/example/zippick/ui/screen/SizeSearchResultScreen.kt
  Zippick/app/src/main/java/com/example/zippick/ui/viewmodel/ProductViewModel.kt
Labels: enhancement

#62 feat:마이페이지 api 연동
  Zippick/app/src/main/java/com/example/zippick/network/RetrofitInstance.kt
  Zippick/app/src/main/java/com/example/zippick/network/auth/AuthService.kt
  Zippick/app/src/main/java/com/example/zippick/network/member/MemberService.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/MainScreenWithBottomNav.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/RequireLogin.kt
  Zippick/app/src/main/java/com/example/zippick/ui/model/MyInfoResponse.kt
  Zippick/app/src/main/java/com/example/zippick/ui/model/OrderHistoryResponse.kt
  Zippick/app/src/main/java/com/example/zippick/ui/screen/LoginScreen.kt
  Zippick/app/src/main/java/com/example/zippick/ui/screen/MyScreen.kt
Labels: feat

#71 feat: 로그인 페이지 수성
  Zippick/app/src/main/java/com/example/zippick/ui/composable/MainScreenWithBottomNav.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/RequireLogin.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/TopBar.kt
  Zippick/app/src/main/java/com/example/zippick/ui/screen/LoginScreen.kt
Labels: feat

#78 bug: 로그인 인터셉터
  Zippick/app/src/main/java/com/example/zippick/ui/composable/TopBar.kt
  Zippick/app/src/main/java/com/example/zippick/ui/composable/detail/ProductDetailContent.kt
  Zippick/app/src/main/java/com/example/zippick/ui/screen/NotificationScreen.kt
Labels: bug
